export interface Car {
  car_id: number,
  price: number,
  brand: string,
  model: string,
  year: number,
  status: string,
  mileage: number,
  color: string,
  vin: string,
  lot: string,
  state: string,
  country: string,
  condition: string,
}
