export interface CarRaw {
  car_id: string,
  price: string,
  brand: string,
  model: string,
  year: string,
  status: string,
  mileage: string,
  color: string,
  vin: string,
  lot: string,
  state: string,
  country: string,
  condition: string,
}
